### ISSUE TITLE
contributed by section broken

### ISSUE THREAD

**Issue by Darryl-Shi** [EC3-Gang/cpp#56]
the contributors section just goes to whoever made the last commit

**Comment by Darryl-Shi** [comment]
me when the

**Comment by DET171** [comment]
provide screenshot argh
i need to add an issue template

**Comment by Darryl-Shi** [comment]
aight aight

**Comment by DET171** [comment]
also its the git plugin's problem

**Comment by Darryl-Shi** [comment]
ok then you still need screenshot?

**Comment by DET171** [comment]
mm git problem

**Comment by DET171** [comment]
ok you can do a pr if my commit doesn't fix

**Comment by DET171** [comment]
works
![image](https://user-images.githubusercontent.com/68373699/155867420-ec8af374-6cc6-41f3-a792-1ea9e57f9a86.png)

**Comment by DET171** [comment]
closing
